
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.4.0+18d5aef85 for .NET Framework
      Build started 2023. 12. 12. 14:35:56.
      Project "F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\3.28.0-rc5\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        E:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        E:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\3.28.0-rc5\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=E:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\3.28.0-rc5\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:01.24
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/3.28.0-rc5/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.4.0+18d5aef85 for .NET Framework
      Build started 2023. 12. 12. 14:35:57.
      Project "F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\3.28.0-rc5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        E:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        E:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\3.28.0-rc5\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=E:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\3.28.0-rc5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:01.09
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/3.28.0-rc5/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/CMakeScratch/TryCompile-fm5msd"
      binary: "F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/CMakeScratch/TryCompile-fm5msd"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/CMakeScratch/TryCompile-fm5msd'
        
        Run Build Command(s): "E:/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_7d1c4.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.4.0+18d5aef85 for .NET Framework
        Build started 2023. 12. 12. 14:35:59.
        Project "F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\CMakeScratch\\TryCompile-fm5msd\\cmTC_7d1c4.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_7d1c4.dir\\Debug\\".
          Creating directory "F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\CMakeScratch\\TryCompile-fm5msd\\Debug\\".
          Creating directory "cmTC_7d1c4.dir\\Debug\\cmTC_7d1c4.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_7d1c4.dir\\Debug\\cmTC_7d1c4.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          E:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_7d1c4.dir\\Debug\\\\" /Fd"cmTC_7d1c4.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31935 for x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_7d1c4.dir\\Debug\\\\" /Fd"cmTC_7d1c4.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          E:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\CMakeScratch\\TryCompile-fm5msd\\Debug\\cmTC_7d1c4.exe" /INCREMENTAL /ILK:"cmTC_7d1c4.dir\\Debug\\cmTC_7d1c4.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/CMakeScratch/TryCompile-fm5msd/Debug/cmTC_7d1c4.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/CMakeScratch/TryCompile-fm5msd/Debug/cmTC_7d1c4.lib" /MACHINE:X64  /machine:x64 cmTC_7d1c4.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_7d1c4.vcxproj -> F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\CMakeScratch\\TryCompile-fm5msd\\Debug\\cmTC_7d1c4.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_7d1c4.dir\\Debug\\cmTC_7d1c4.tlog\\unsuccessfulbuild".
          Touching "cmTC_7d1c4.dir\\Debug\\cmTC_7d1c4.tlog\\cmTC_7d1c4.lastbuildstate".
        Done Building Project "F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\CMakeScratch\\TryCompile-fm5msd\\cmTC_7d1c4.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:01.17
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/CMakeScratch/TryCompile-5v1ezl"
      binary: "F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/CMakeScratch/TryCompile-5v1ezl"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/CMakeScratch/TryCompile-5v1ezl'
        
        Run Build Command(s): "E:/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_64709.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.4.0+18d5aef85 for .NET Framework
        Build started 2023. 12. 12. 14:36:00.
        Project "F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\CMakeScratch\\TryCompile-5v1ezl\\cmTC_64709.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_64709.dir\\Debug\\".
          Creating directory "F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\CMakeScratch\\TryCompile-5v1ezl\\Debug\\".
          Creating directory "cmTC_64709.dir\\Debug\\cmTC_64709.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_64709.dir\\Debug\\cmTC_64709.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          E:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_64709.dir\\Debug\\\\" /Fd"cmTC_64709.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31935 for x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_64709.dir\\Debug\\\\" /Fd"cmTC_64709.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          E:\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\CMakeScratch\\TryCompile-5v1ezl\\Debug\\cmTC_64709.exe" /INCREMENTAL /ILK:"cmTC_64709.dir\\Debug\\cmTC_64709.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/CMakeScratch/TryCompile-5v1ezl/Debug/cmTC_64709.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"F:/SZE/5/Mosze/mosze-2023-hw-pacman-bytebusters/ByteBusters/Game/CMakeBuild/CMakeFiles/CMakeScratch/TryCompile-5v1ezl/Debug/cmTC_64709.lib" /MACHINE:X64  /machine:x64 cmTC_64709.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_64709.vcxproj -> F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\CMakeScratch\\TryCompile-5v1ezl\\Debug\\cmTC_64709.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_64709.dir\\Debug\\cmTC_64709.tlog\\unsuccessfulbuild".
          Touching "cmTC_64709.dir\\Debug\\cmTC_64709.tlog\\cmTC_64709.lastbuildstate".
        Done Building Project "F:\\SZE\\5\\Mosze\\mosze-2023-hw-pacman-bytebusters\\ByteBusters\\Game\\CMakeBuild\\CMakeFiles\\CMakeScratch\\TryCompile-5v1ezl\\cmTC_64709.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:01.02
        
      exitCode: 0
...
